<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hel.Application\Hel.Application.csproj" />
    <ProjectReference Include="..\Hel.Domain\Hel.Domain.csproj" />
  </ItemGroup>

</Project>
